#
# Makefile for the linux NOVA filesystem routines.
#

obj-$(CONFIG_NOVA_FS) += nova.o

nova-y := balloc.o bbuild.o dax.o dir.o file.o inode.o ioctl.o journal.o namei.o stats.o super.o symlink.o wprotect.o
